Reworked the read me, to have valid instructions on execution, saved …
Will513r/React-blog pull request #1
Opened 2024-06-29 20:49 UTC by ChrisForti

…eslint config. instructions (We probably will not need them). Also added some devicons to dress it up a bit.

2024-06-29 20:59 UTC, kensonjohnson requested changes

2024-06-29 20:59 UTC, kensonjohnson commented on README.md
>  ## Expanding the ESLint configuration
This entire portion talking about ESLint configuration can go away

2024-06-29 21:14 UTC, kensonjohnson approved these changes
:shipit:

2024-07-05 23:14 UTC, Will513r reviewed
LGTM

2024-07-05 23:17 UTC, Will513r approved these changes

2024-07-05 23:19 UTC, michaelatimore approved these changes

2024-07-05 23:20 UTC, merged